### ISSUE TITLE
DbCon.java 

### ISSUE THREAD

**Issue by FearxBlaze** [Almamun-Hossain/jsp-ecommerce#1]
Hi !, I have a problem with the DbCon .. I am following the tutorials, but I cannot get the DbCon to work .. it gives me an error in the "index.jsp"

I attach Screen

(Srry for the bad english =P)

![image](https://user-images.githubusercontent.com/102036897/166968180-09109598-4ac3-4b3b-a117-bba6352b2cb7.png)
![image](https://user-images.githubusercontent.com/102036897/166968227-c8812cb4-8cc7-4b1c-8aed-83269c11fa61.png)
![image](https://user-images.githubusercontent.com/102036897/166968682-99b6fc63-8ea0-4cd4-86b3-b98e8a2137e6.png)

**Comment by Almamun-Hossain** [comment]
I just reviewed your code. seems your package name and the static Connection variable name are same. Could you please define two different name? "Connection" is a reserved keyword.

**Comment by FearxBlaze** [comment]
can you show me what are the error? because i'm trying changing everything but still doesn't work

**Comment by Almamun-Hossain** [comment]
![Image 2022-05-08 22-27-16](https://user-images.githubusercontent.com/43817775/167305720-c652e496-85e1-47bb-bb32-faf990d230c6.png)
I am assuming this is causing the issue.

**Comment by FearxBlaze** [comment]
changed, but still error.. can you help me on anydesk?

**Comment by sajidshah232** [comment]
did your problem solve? i am facing same problem, can you help?

**Comment by Almamun-Hossain** [comment]
Hi @FearxBlaze, after changing the package name have you imported the package to your index.jsp page? After checking your index.jsp page I can't see any package import. To import package please use 
`<%@page import="your-package-name"%>`
Here is an example:
`<%@page import="cn.techtutorial.connection.DbCon"%>`

![image](https://user-images.githubusercontent.com/43817775/214675574-8a07db13-75d6-43ad-8381-ad1ac0d348f9.png)

**Comment by sajidshah232** [comment]
bro i did all the things, can i get your whatsapp no.? my contact no. is
+60183546282

**Comment by Almamun-Hossain** [comment]
Seems the problem has been fixed. :)
